# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Welcome to Dev Island!"
description: > # this means to ignore newlines until "email:"

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/author.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/background_image.png"

name: 'Daniel Krzyczkowski'
author: 'Daniel Krzyczkowski'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@DKrzyczkowski'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/DKrzyczkowski
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/daniel-krzyczkowski
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
